// Seed reviews dataset for the /reviews page. Noah will swap in real
// testimonials before launch — keep the shape identical when editing.
// Stars are 1-5. Tags drive the filter chips. dateISO is YYYY-MM-DD.

export const REVIEWS = [
  {
    id: "r-aiden-d",
    name: "Aiden D.",
    location: "Phoenix, AZ",
    stars: 5,
    dateISO: "2026-05-22",
    headline: "$11k month two — coaching is unreal",
    body: "Joined in February with zero ads experience. Got my first paying brand by week three and hit $11k in cash collected by month two. The coaching calls every Monday and Wednesday are what actually moved the needle — not just the curriculum.",
    tags: ["beginner", "first-client", "coaching"],
    avatarBg: "#FF6B35",
  },
  {
    id: "r-jared-l",
    name: "Jared L.",
    location: "Toronto, ON",
    stars: 5,
    dateISO: "2026-05-18",
    headline: "Replaced my W-2 income in 4 months",
    body: "I was a setter at a SaaS company making $7k/mo. Four months into the program I'm at $9.4k/mo from two retainers and quit my job last week. The Athena setup made the difference for me — outreach finally got predictable.",
    tags: ["retainers", "quit-job", "athena"],
    avatarBg: "#3A86FF",
  },
  {
    id: "r-raj-t",
    name: "Raj T.",
    location: "Birmingham, UK",
    stars: 5,
    dateISO: "2026-05-12",
    headline: "Closed $18k in commissions last month",
    body: "Came in skeptical — already running a small agency that was stuck at $4-6k MRR. Eight weeks in, the offer rework alone bumped me to $18k cash collected last month. Mission Control is the missing piece every agency owner doesn't know they need.",
    tags: ["existing-agency", "offer-rework", "mission-control"],
    avatarBg: "#06A77D",
  },
  {
    id: "r-isaiah-a",
    name: "Isaiah A.",
    location: "Lagos, Nigeria",
    stars: 5,
    dateISO: "2026-05-05",
    headline: "Best $4.8k I've ever spent",
    body: "Was working a 9-5 making $400/month. Took the leap and joined the program in January. Three months later closed my first US-based client at $2k/mo. Now I run ads from a co-working space in Lagos and bill in dollars. Life-changing.",
    tags: ["international", "first-client", "beginner"],
    avatarBg: "#9D4EDD",
  },
  {
    id: "r-will-w",
    name: "Will W.",
    location: "Austin, TX",
    stars: 5,
    dateISO: "2026-04-29",
    headline: "Eight closes on one day in week six",
    body: "The Brez script + the systems combo is what makes this work. I had a day in week 6 where I closed eight prospects on appointment-setting calls. Made $410 in commissions that day alone. Nothing else I've bought has produced numbers like that.",
    tags: ["coaching", "high-volume", "scripts"],
    avatarBg: "#F26430",
  },
  {
    id: "r-hank-v",
    name: "Hank V.",
    location: "Charlotte, NC",
    stars: 5,
    dateISO: "2026-04-21",
    headline: "Replaced a 12-hour days job with this",
    body: "Was wrenching cars 60 hours a week. Joined to build something on the side. Six months in I'm doing ads for three e-com brands and pulling more in commissions than I was at the shop. Sold my truck last week to buy a quieter one for client calls.",
    tags: ["side-hustle", "career-change", "retainers"],
    avatarBg: "#264653",
  },
  {
    id: "r-jared-l-2",
    name: "Jared L.",
    location: "Toronto, ON",
    stars: 5,
    dateISO: "2026-04-15",
    headline: "Speed-to-lead is the unlock",
    body: "The biggest single thing the program teaches that nobody else does is speed-to-lead under two minutes. Once I dialed that in, my show rate jumped from 50% to 78%. That alone paid for the program in a month.",
    tags: ["speed-to-lead", "show-rate", "tactics"],
    avatarBg: "#3A86FF",
  },
  {
    id: "r-noah-e",
    name: "Noah E.",
    location: "San Diego, CA",
    stars: 5,
    dateISO: "2026-04-09",
    headline: "From 0 to $7k MRR in 90 days",
    body: "I had $0 in agency revenue when I started. The curriculum is good but it's the community — the daily wins shared in the Discord — that keeps you accountable. Hit $7k MRR exactly 90 days in. Now scaling toward $15k.",
    tags: ["community", "first-client", "discord"],
    avatarBg: "#E63946",
  },
  {
    id: "r-jake-d",
    name: "Jake D.",
    location: "Brisbane, AU",
    stars: 5,
    dateISO: "2026-04-02",
    headline: "Closed one of the biggest deals of my life",
    body: "Australia-based, was scared this wouldn't translate. It does — the principles travel. Closed my biggest deal ever ($24k upfront) eight weeks in using the Brez pitch framework. The hand-holding on the close itself is unreal.",
    tags: ["international", "big-deal", "framework"],
    avatarBg: "#2A9D8F",
  },
  {
    id: "r-alex-s",
    name: "Alex S.",
    location: "Brooklyn, NY",
    stars: 5,
    dateISO: "2026-03-28",
    headline: "The offer breakdown changed everything",
    body: "Had a 'good' offer for two years that wasn't getting traction. Two coaching calls into the program, Pierre tore it apart and rebuilt it. Tested the new version that week, closed 3 of 8 demos. Three. Of eight. From a 1-in-15 baseline.",
    tags: ["offer-rework", "coaching", "conversion"],
    avatarBg: "#FF006E",
  },
  {
    id: "r-xavier-z",
    name: "Xavier Z.",
    location: "Madrid, Spain",
    stars: 5,
    dateISO: "2026-03-22",
    headline: "I almost dropped out — glad I didn't",
    body: "Honestly, weeks 2-3 I thought about quitting. Felt overwhelmed. Reached out in Discord, Aiden jumped on a call with me at 11pm his time. By week 5 I had my first deposit. Now I'm at $4.2k/mo from one client. The support is real.",
    tags: ["support", "perseverance", "first-client"],
    avatarBg: "#FFB703",
  },
  {
    id: "r-braeden-r",
    name: "Braeden R.",
    location: "Salt Lake City, UT",
    stars: 5,
    dateISO: "2026-03-15",
    headline: "Best community for this niche, hands down",
    body: "Been in five other 'agency' programs. None of them have the depth Brez has on actually closing high-ticket. The role-play sessions weekly are brutal but that's what got me from 'I think I can sell' to actually doing it.",
    tags: ["community", "sales-training", "roleplay"],
    avatarBg: "#8338EC",
  },
];

export const ALL_TAGS = [...new Set(REVIEWS.flatMap((r) => r.tags))].sort();

export const REVIEW_STATS = {
  total: REVIEWS.length,
  avgStars: (
    REVIEWS.reduce((sum, r) => sum + r.stars, 0) / REVIEWS.length
  ).toFixed(1),
  fiveStarCount: REVIEWS.filter((r) => r.stars === 5).length,
};
